import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "app_language";

const MESSAGES = {
  vi: {
    today: "Hôm nay",
    courts: "Sân",
    noCourtsYet: "Chưa có sân nào.",
    bookNow: "ĐẶT LỊCH",
    notifications: "Thông báo",
    noNewNotifications: "Bạn chưa có thông báo mới.",
    languageTitle: "Ngôn ngữ",
    languagePrompt: "Chọn ngôn ngữ hiển thị",
    vietnamese: "Tiếng Việt",
    english: "Tiếng Anh",
    map: "Bản đồ",
    cannotOpenGoogleMaps: "Không thể mở liên kết Google Maps.",
    openMap: "Mở bản đồ",
    chooseMapView: "Chọn cách xem vị trí sân.",
    cancel: "Hủy",
    defaultMaps: "Bản đồ mặc định",
    googleMaps: "Google Maps",
    error: "Lỗi",
    loadCourtDetailsFailed: "Không thể tải chi tiết sân.",
    bookingFailed: "Đặt lịch thất bại",
    missingCourtOrSlot: "Thiếu thông tin sân hoặc khung giờ.",
    bookingSuccessTitle: "Thành công",
    bookingSuccessMessage: "Đặt lịch thành công!",
    courtNotFound: "Không tìm thấy sân",
    bookCourt: "Đặt lịch sân",
    viewCourtOnMap: "Xem vị trí trên bản đồ",
    openMapInline: "Mở bản đồ",
    noRatingYet: "Chưa có đánh giá",
    tabInfo: "Thông tin",
    tabService: "Dịch vụ",
    tabImages: "Hình ảnh",
    tabTerms: "Điều khoản & quy định",
    tabReviews: "Đánh giá",
    availableSlots: "Khung giờ khả dụng",
    noAvailableSlots: "Không có khung giờ trống cho hôm nay.",
    available: "Còn trống",
    booked: "Đã đặt",
    book: "Đặt",
    noImages: "Chưa có hình ảnh.",
    comingSoonContent: "Nội dung sẽ được cập nhật trong phiên bản tiếp theo.",
    settingsTitle: "Cài đặt",
    settingsNotifications: "Thông báo",
    settingsLanguage: "Ngôn ngữ",
    settingsTheme: "Chế độ sáng/tối",
    settingsLight: "Sáng",
    settingsDark: "Tối",
    settingsLogout: "Đăng xuất tài khoản",
    settingsDeleteAccount: "Xóa tài khoản",
    settingsChooseLanguage: "Chọn ngôn ngữ",
    settingsLogoutFailedTitle: "Đăng xuất thất bại",
    settingsLogoutFailedMessage: "Không thể đăng xuất lúc này.",
    settingsThemeFailedTitle: "Giao diện",
    settingsThemeFailedMessage: "Không thể đổi chế độ sáng/tối lúc này.",
    settingsDeleteConfirmTitle: "Xóa tài khoản",
    settingsDeleteConfirmMessage: "Bạn có muốn xóa vĩnh viễn tài khoản không?",
    settingsDeleteConfirmAction: "Xóa vĩnh viễn",
    settingsDeleteFailedTitle: "Xóa tài khoản thất bại",
    settingsDeleteFailedMessage: "Không thể xóa tài khoản.",
    tabHome: "Trang chủ",
    tabSearch: "Tìm kiếm",
    tabManage: "Quản lý",
    tabCourts: "Sân",
    tabSchedule: "Lịch",
    tabBookings: "Đặt sân",
    tabProfile: "Hồ sơ",
    tabSettings: "Cài đặt",
    homeHeroTitle: "Tìm sân của bạn",
    homeHeroSubtitle: "Đặt sân tennis phù hợp gần bạn",
    homeSearchPlaceholder: "Tìm sân theo tên hoặc địa điểm...",
    homeNearbyCourts: "Sân gần bạn",
    homeCourtsCount: "sân",
    homeNoCourtsFound: "Không tìm thấy sân nào.",
    viewDetails: "XEM CHI TIẾT",
    courtTagDaily: "Đơn ngày",
    courtTagEvent: "Sự kiện",
    court: "Sân",
    user: "Người dùng",
    emailNotUpdated: "Chưa cập nhật email",
    featureUpdating: "Tính năng đang được cập nhật.",
    profileQuickBookings: "Lịch đã đặt",
    profileQuickNotifications: "Thông báo",
    profileQuickCourses: "Khóa học",
    profileQuickOffers: "Ưu đãi",
    profileActivityTeam: "Nhóm của tôi",
    profileActivityLessons: "Danh sách lịch học",
    profileActivityMembership: "Gói hội viên",
    profileSystemSettings: "Cài đặt",
    profileSystemVersion: "Thông tin phiên bản",
    profileSystemPolicy: "Điều khoản và chính sách",
    profileSystemNews: "Ứng dụng có gì mới",
    profileSectionActivity: "Hoạt động",
    profileSectionSystem: "Hệ thống",
    profileVersionPrefix: "Thông tin phiên bản",
    filterAll: "Tất cả",
    filterUpcoming: "Sắp tới",
    filterPast: "Đã qua",
    bookingsLoadFailed: "Không thể tải danh sách đặt sân.",
    bookingsCancelSuccess: "Hủy đặt sân thành công.",
    bookingsCancelFailed: "Không thể hủy đặt sân.",
    bookingsCancelTitle: "Hủy đặt sân",
    bookingsCancelConfirm: "Bạn có chắc muốn hủy lịch đặt này không?",
    bookingsPaymentSuccess: "Xác nhận thanh toán thành công.",
    bookingsPaymentError: "Lỗi thanh toán",
    bookingsPaymentErrorMessage: "Không thể xác nhận thanh toán.",
    bookingsAllTitle: "Tất cả đặt sân",
    bookingsTitleSuffix: "đặt sân",
    bookingsNoItemsInFilter: "Không có lịch đặt trong bộ lọc này.",
    bookingsProcessing: "Đang xử lý...",
    bookingsConfirmPayment: "Xác nhận thanh toán",
    bookingsCancelAction: "Hủy đặt sân",
    payment: "Thanh toán",
    paymentPaid: "Đã thanh toán",
    paymentUnpaid: "Chưa thanh toán",
    statusPending: "Chờ xác nhận",
    statusConfirmed: "Đã xác nhận",
    statusCompleted: "Hoàn thành",
    statusCancelled: "Đã hủy",
    no: "Không",
    yes: "Có",
    notificationSectionFresh: "Mới",
    notificationSectionToday: "Hôm nay",
    notificationSectionPrevious: "Trước đó",
    notificationMinutes: "phút",
    notificationHours: "giờ",
    notificationDays: "ngày",
    notificationMarkAllRead: "Đã đọc hết",
    notificationUnread: "Chưa đọc",
    notificationUnreadCount: "Chưa đọc",
    notificationEmpty: "Không có thông báo.",
    notificationViewAll: "Xem tất cả",
    favorite: "Yêu thích",
    favoriteUpdateFailed: "Không thể cập nhật trạng thái yêu thích lúc này.",
    contact: "Liên hệ",
    contactCannotOpenLink: "Không mở được liên kết này.",
    contactCannotCall: "Không thể gọi số này trên thiết bị hiện tại.",
    contactPhoneAction: "Liên hệ số điện thoại",
    contactFacebookAction: "Liên hệ Facebook",
    contactZaloAction: "Liên hệ Zalo",
  },
  en: {
    today: "Today",
    courts: "Courts",
    noCourtsYet: "No courts yet.",
    bookNow: "BOOK NOW",
    notifications: "Notifications",
    noNewNotifications: "You have no new notifications.",
    languageTitle: "Language",
    languagePrompt: "Choose display language",
    vietnamese: "Vietnamese",
    english: "English",
    map: "Map",
    cannotOpenGoogleMaps: "Cannot open Google Maps link.",
    openMap: "Open map",
    chooseMapView: "Choose how you want to view this location.",
    cancel: "Cancel",
    defaultMaps: "Default Maps",
    googleMaps: "Google Maps",
    error: "Error",
    loadCourtDetailsFailed: "Failed to load court details.",
    bookingFailed: "Booking failed",
    missingCourtOrSlot: "Court or slot information is missing.",
    bookingSuccessTitle: "Success",
    bookingSuccessMessage: "Booking created successfully!",
    courtNotFound: "Court not found",
    bookCourt: "Book court",
    viewCourtOnMap: "View court location on map",
    openMapInline: "Open map",
    noRatingYet: "No rating yet",
    tabInfo: "Info",
    tabService: "Service",
    tabImages: "Images",
    tabTerms: "Terms & policy",
    tabReviews: "Reviews",
    availableSlots: "Available slots",
    noAvailableSlots: "No available slots for today.",
    available: "Available",
    booked: "Booked",
    book: "Book",
    noImages: "No images.",
    comingSoonContent: "Content will be updated in the next version.",
    settingsTitle: "Settings",
    settingsNotifications: "Notifications",
    settingsLanguage: "Language",
    settingsTheme: "Light/Dark mode",
    settingsLight: "Light",
    settingsDark: "Dark",
    settingsLogout: "Log out",
    settingsDeleteAccount: "Delete account",
    settingsChooseLanguage: "Choose language",
    settingsLogoutFailedTitle: "Logout failed",
    settingsLogoutFailedMessage: "Unable to log out right now.",
    settingsThemeFailedTitle: "Appearance",
    settingsThemeFailedMessage: "Unable to switch light/dark mode right now.",
    settingsDeleteConfirmTitle: "Delete account",
    settingsDeleteConfirmMessage: "Do you want to permanently delete this account?",
    settingsDeleteConfirmAction: "Delete permanently",
    settingsDeleteFailedTitle: "Delete account failed",
    settingsDeleteFailedMessage: "Unable to delete this account.",
    tabHome: "Home",
    tabSearch: "Search",
    tabManage: "Manage",
    tabCourts: "Courts",
    tabSchedule: "Schedule",
    tabBookings: "Bookings",
    tabProfile: "Profile",
    tabSettings: "Settings",
    homeHeroTitle: "Find Your Court",
    homeHeroSubtitle: "Book the perfect tennis court near you",
    homeSearchPlaceholder: "Search courts by name or location...",
    homeNearbyCourts: "Nearby Courts",
    homeCourtsCount: "courts",
    homeNoCourtsFound: "No courts found.",
    viewDetails: "VIEW DETAILS",
    courtTagDaily: "Daily",
    courtTagEvent: "Event",
    court: "Court",
    user: "User",
    emailNotUpdated: "Email not updated",
    featureUpdating: "This feature is being updated.",
    profileQuickBookings: "My Bookings",
    profileQuickNotifications: "Notifications",
    profileQuickCourses: "Courses",
    profileQuickOffers: "Offers",
    profileActivityTeam: "My Team",
    profileActivityLessons: "Lesson Schedule",
    profileActivityMembership: "Membership Packages",
    profileSystemSettings: "Settings",
    profileSystemVersion: "Version Info",
    profileSystemPolicy: "Terms and Policies",
    profileSystemNews: "What's New",
    profileSectionActivity: "Activity",
    profileSectionSystem: "System",
    profileVersionPrefix: "Version",
    filterAll: "All",
    filterUpcoming: "Upcoming",
    filterPast: "Past",
    bookingsLoadFailed: "Failed to load bookings.",
    bookingsCancelSuccess: "Booking cancelled successfully.",
    bookingsCancelFailed: "Failed to cancel booking.",
    bookingsCancelTitle: "Cancel Booking",
    bookingsCancelConfirm: "Are you sure you want to cancel this booking?",
    bookingsPaymentSuccess: "Payment confirmed successfully.",
    bookingsPaymentError: "Payment Error",
    bookingsPaymentErrorMessage: "Unable to confirm payment.",
    bookingsAllTitle: "All Bookings",
    bookingsTitleSuffix: "Bookings",
    bookingsNoItemsInFilter: "No bookings in this filter.",
    bookingsProcessing: "Processing...",
    bookingsConfirmPayment: "Confirm Payment",
    bookingsCancelAction: "Cancel Booking",
    payment: "Payment",
    paymentPaid: "Paid",
    paymentUnpaid: "Unpaid",
    statusPending: "Pending",
    statusConfirmed: "Confirmed",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    no: "No",
    yes: "Yes",
    notificationSectionFresh: "New",
    notificationSectionToday: "Today",
    notificationSectionPrevious: "Previous",
    notificationMinutes: "minutes",
    notificationHours: "hours",
    notificationDays: "days",
    notificationMarkAllRead: "Mark all read",
    notificationUnread: "Unread",
    notificationUnreadCount: "Unread",
    notificationEmpty: "No notifications.",
    notificationViewAll: "View all",
    favorite: "Favorite",
    favoriteUpdateFailed: "Unable to update favorite right now.",
    contact: "Contact",
    contactCannotOpenLink: "Cannot open this link.",
    contactCannotCall: "Cannot call this number on this device.",
    contactPhoneAction: "Contact by phone",
    contactFacebookAction: "Contact on Facebook",
    contactZaloAction: "Contact on Zalo",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("vi");

  useEffect(() => {
    const load = async () => {
      try {
        const stored = await AsyncStorage.getItem(STORAGE_KEY);
        if (stored === "vi" || stored === "en") {
          setLanguage(stored);
        }
      } catch {
        // ignore storage failures
      }
    };
    load();
  }, []);

  const changeLanguage = async (nextLanguage) => {
    if (nextLanguage !== "vi" && nextLanguage !== "en") {
      return;
    }
    setLanguage(nextLanguage);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, nextLanguage);
    } catch {
      // ignore storage failures
    }
  };

  const value = useMemo(() => {
    const dictionary = MESSAGES[language] || MESSAGES.vi;
    return {
      language,
      setLanguage: changeLanguage,
      t: (key) => dictionary[key] || MESSAGES.vi[key] || key,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider.");
  }
  return context;
}
