import {
  AdminCourtsScreen,
  AdminDashboardScreen,
  AdminReportsScreen,
  AdminUsersScreen,
  LoginScreen,
  RegisterScreen,
  UserBookingsScreen,
  UserHomeScreen,
  UserMainScreen,
  UserProfileScreen,
  UserSearchScreen,
  VendorBookingsScreen,
  VendorCourtsScreen,
  VendorDashboardScreen,
  VendorScheduleScreen,
} from "../screens";

export const screenRegistry = {
  LoginScreen,
  RegisterScreen,
  UserMainScreen,
  UserHomeScreen,
  UserSearchScreen,
  UserBookingsScreen,
  UserProfileScreen,
  VendorDashboardScreen,
  VendorCourtsScreen,
  VendorScheduleScreen,
  VendorBookingsScreen,
  AdminDashboardScreen,
  AdminUsersScreen,
  AdminCourtsScreen,
  AdminReportsScreen,
};
