import {
  AdminCourtsScreen,
  AdminDashboardScreen,
  AdminMainScreen,
  AdminReportsScreen,
  AdminUsersScreen,
  ForgotPasswordScreen,
  LoginScreen,
  RegisterScreen,
  OwnerBookingsScreen,
  OwnerCourtsScreen,
  OwnerDashboardScreen,
  OwnerMainScreen,
  OwnerScheduleScreen,
  UserBookingsScreen,
  UserHomeScreen,
  UserMainScreen,
  UserProfileScreen,
} from "../screens";

export const screenRegistry = {
  LoginScreen,
  RegisterScreen,
  ForgotPasswordScreen,
  UserMainScreen,
  UserHomeScreen,
  UserBookingsScreen,
  UserProfileScreen,
  OwnerDashboardScreen,
  OwnerMainScreen,
  OwnerCourtsScreen,
  OwnerScheduleScreen,
  OwnerBookingsScreen,
  AdminDashboardScreen,
  AdminMainScreen,
  AdminUsersScreen,
  AdminCourtsScreen,
  AdminReportsScreen,
};
